set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR STM32F401)

#if(MINGW OR CYGWIN OR WIN32)
#    set(UTIL_SEARCH_CMD where)
#elseif(UNIX OR APPLE)
#    set(UTIL_SEARCH_CMD which)
#endif()

set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)

set(CMAKE_GENERATOR "Unix Makefiles")

set(TOOLCHAIN_PREFIX arm-none-eabi-)

execute_process(
  COMMAND ${UTIL_SEARCH_CMD} ${TOOLCHAIN_PREFIX}gcc
  OUTPUT_VARIABLE BINUTILS_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

get_filename_component(ARM_TOOLCHAIN_DIR ${BINUTILS_PATH} DIRECTORY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

#set(CMAKE_C_COMPILER 	${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_C_COMPILER 	"D:/ARM/9 2020-q2-update/bin/arm-none-eabi-gcc.exe")
set(CMAKE_ASM_COMPILER 	${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER 	${TOOLCHAIN_PREFIX}g++)
set(AS                  ${TOOLCHAIN_PREFIX}as)
set(AR                  ${TOOLCHAIN_PREFIX}ar)
set(OBJCOPY             ${TOOLCHAIN_PREFIX}objcopy)
set(OBJDUMP             ${TOOLCHAIN_PREFIX}objdump)
set(SIZE                ${TOOLCHAIN_PREFIX}size)

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${ARM_TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)