set(sources
    ${common_sources}
    Application/Application/Led/Src/LED.c
    Application/Application/Led/Cfg/LED_Cfg.c
    Application/Src/application.c
    Application/Communication/Network/Src/Ethernet.c
    Application/Communication/Network/Cfg/Ethernet_Cfg.c
    Application/Communication/Modbus/RTUMaster/ModbusRTUMaster.c
    Application/Communication/Modbus/TCPServer/ModbusTCPServer.c
    Application/DeviceDrivers/DAC/Src/DAC.c
    Application/DeviceDrivers/Ethernet/socket.c
    Application/DeviceDrivers/Ethernet/wizchip_conf.c
    Application/DeviceDrivers/Ethernet/W5500/w5500.c
    Application/DeviceDrivers/EEPROM/Src/EEPROM.c
    Application/DeviceDrivers/EnergyMeter/Src/EnergyMeter.c
    Application/DeviceDrivers/Heater/Src/Heater.c
    Application/DeviceDrivers/Heater/Cfg/Heater_Cfg.c
    Application/DeviceDrivers/HMI/Src/HMI_SWUpdate.c
    Application/DeviceDrivers/MCP23017/Src/MCP23017.c
    Application/DeviceDrivers/MCU/HALHelpers/HALHelpers.c
    Application/DeviceDrivers/MCU/MCU_SWUpdate/Src/MCU_SWUpdate.c
    Application/DeviceDrivers/W25Qxx/Src/w25qxx.c
    Application/Libraries/sys/syscalls.c
    Application/Libraries/sys/sysmem.c
    Application/Services/CLI/FreeRTOS_CLI/FreeRTOS_CLI.c
    Application/Services/CLI/Src/CLI.c
    Application/Services/ConfigMgr/Src/ConfigMgr.c
    Application/Services/DateTimeMgr/Src/DateTimeMgr.c
    Application/Services/EventLog/Src/EventLog.c
    Application/Services/I2CGpio/Src/I2CGpio.c
    Application/Services/Internet/DNS/dns.c
    Application/Services/Internet/SNTP/sntp.c
    Application/Services/ResourceGuard/Src/ResourceGuard.c
    Application/Services/RuntimeStats/Src/CommStats.c
    Application/Services/SPIFlash/Src/SPI_Flash.c
    Application/Services/SWUpdate/Src/SWUpdate.c
    Core/Src/main.c
    Core/Src/logging.c
    Core/Src/gpio.c
    Core/Src/crc.c
    Core/Src/fdcan.c
    Core/Src/i2c.c
    Core/Src/rtc.c
    Core/Src/spi.c
    Core/Src/usart.c
    Core/Src/stm32g0xx_it.c
    Core/Src/stm32g0xx_hal_msp.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_crc.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_crc_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_exti.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_fdcan.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rtc.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rtc_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart_ex.c
    Core/Src/system_stm32g0xx.c
    Core/Src/stm32g0xx_hal_timebase_tim.c
    Core/Src/tim.c
    Core/Src/adc.c
    Core/Src/dma.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_adc.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_adc_ex.c
    Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_adc.c
)

set(includes
    ${common_includes}
    Application/Src
    Application/Application/Led/Src
    Application/Application/Led/Cfg
    Application/Communication/Network/Src
    Application/Communication/Network/Cfg
    Application/Communication/Modbus/RTUMaster
    Application/Communication/Modbus/TCPServer
    Application/DeviceDrivers/DAC/Src
    Application/DeviceDrivers/EEPROM/Src
    Application/DeviceDrivers/Ethernet
    Application/DeviceDrivers/Ethernet/W5500
    Application/DeviceDrivers/EnergyMeter/Src
    Application/DeviceDrivers/Heater/Src
    Application/DeviceDrivers/Heater/Cfg
    Application/DeviceDrivers/HMI/Src
    Application/DeviceDrivers/MCP23017/Src
    Application/DeviceDrivers/MCU/MCU_SWUpdate/Src
    Application/DeviceDrivers/W25Qxx/Src
    Application/DeviceDrivers/W25Qxx/Cfg
    Application/Services/CLI/FreeRTOS_CLI
    Application/Services/CLI/Src
    Application/Services/ConfigMgr/Src
    Application/Services/DateTimeMgr/Src
    Application/Services/EventLog/Src
    Application/Services/I2CGpio/Src
    Application/Services/Internet/DNS
    Application/Services/Internet/SNTP
    Application/Services/printf
    Application/Services/ResourceGuard/Src
    Application/Services/RuntimeStats/Src
    Application/Services/SPIFlash/Src
    Application/Services/SPIFlash/Cfg
    Application/Services/SWUpdate/Src
    Core/Inc
    Drivers/STM32G0xx_HAL_Driver/Inc
    Drivers/STM32G0xx_HAL_Driver/Inc/Legacy
    Drivers/CMSIS/Device/ST/STM32G0xx/Include
    Drivers/CMSIS/Include
)